import type { ConstellationData } from './types';

export const DEFAULT_DATA: ConstellationData = {
  nodes: [
    // Hub
    {
      id: 'hub',
      label: 'LPE',
      type: 'hub',
      depth: 0,
      title: 'Laboratoire de la Puissance Européenne',
      body: 'Creuset d\'analyses stratégiques sur les souverainetés française et européenne. Nous cartographions les interdépendances qui structurent la puissance.',
      stat: '4',
      statLabel: 'piliers de souveraineté',
    },

    // Pillar 1 — Industrielle (225°)
    {
      id: 'p-indus',
      label: 'Industrielle',
      type: 'pillar',
      depth: 1,
      title: 'Souveraineté Industrielle',
      body: 'Capacité à concevoir, produire et maintenir sur le territoire européen les biens stratégiques : défense, mobilité, pharmacie, matériaux critiques.',
      stat: '38%',
      statLabel: 'de la valeur ajoutée UE perdue depuis 2000',
      worksUrl: '#',
    },
    {
      id: 's-defense',
      label: 'Défense & armement',
      type: 'subtheme',
      parentId: 'p-indus',
      depth: 2,
      title: 'Base industrielle de défense',
      body: 'L\'EDIP et le fonds européen de défense cherchent à consolider une BITD commune. Enjeu : interopérabilité et commandes mutualisées.',
      stat: '€100Mds',
      statLabel: 'investissements défense UE d\'ici 2030',
    },
    {
      id: 's-pharma',
      label: 'Pharma & santé',
      type: 'subtheme',
      parentId: 'p-indus',
      depth: 2,
      title: 'Réindustrialisation pharmaceutique',
      body: 'La dépendance asiatique pour les principes actifs a révélé la fragilité de la chaîne du médicament. Le projet IPCEI Santé entend corriger cela.',
      stat: '80%',
      statLabel: 'des APIs fabriqués hors Europe',
    },
    {
      id: 's-aerospace',
      label: 'Aéronautique & espace',
      type: 'subtheme',
      parentId: 'p-indus',
      depth: 2,
      title: 'Leadership aérospatial',
      body: 'Airbus, Ariane, MBDA : l\'Europe détient des pôles d\'excellence mais leur financement public reste insuffisant face à la concurrence américano-chinoise.',
      stat: '1er',
      statLabel: 'exportateur mondial d\'avions civils',
    },

    // Pillar 2 — Alimentaire (45°)
    {
      id: 'p-alim',
      label: 'Alimentaire',
      type: 'pillar',
      depth: 1,
      title: 'Souveraineté Alimentaire',
      body: 'Capacité à nourrir la population européenne avec une production locale résiliente, face au dérèglement climatique et aux chocs d\'approvisionnement.',
      stat: '27%',
      statLabel: 'des terres agricoles UE sous tension hydrique',
      worksUrl: '#',
    },
    {
      id: 's-pac',
      label: 'PAC & agriculture',
      type: 'subtheme',
      parentId: 'p-alim',
      depth: 2,
      title: 'Politique agricole commune',
      body: 'La PAC représente 31% du budget UE mais doit concilier compétitivité, transition verte et résilience. Sa réforme 2023 a arbitré en faveur de la production.',
      stat: '€387Mds',
      statLabel: 'budget PAC 2023–2027',
    },
    {
      id: 's-semences',
      label: 'Semences & biodiversité',
      type: 'subtheme',
      parentId: 'p-alim',
      depth: 2,
      title: 'Contrôle des semences',
      body: 'Quatre groupes contrôlent 60% du marché mondial des semences. La dépendance aux variétés hybrides brevetées fragilise l\'autonomie des agriculteurs.',
      stat: '4',
      statLabel: 'multinationales contrôlent 60% des semences',
    },
    {
      id: 's-eau',
      label: 'Eau & irrigation',
      type: 'subtheme',
      parentId: 'p-alim',
      depth: 2,
      title: 'Gestion de l\'eau agricole',
      body: 'L\'agriculture consomme 70% des prélèvements d\'eau douce en Europe. La compétition avec les usages urbains et industriels s\'intensifie.',
      stat: '70%',
      statLabel: 'de l\'eau douce dédiée à l\'agriculture',
    },

    // Pillar 3 — Énergétique (315°)
    {
      id: 'p-energie',
      label: 'Énergétique',
      type: 'pillar',
      depth: 1,
      title: 'Souveraineté Énergétique',
      body: 'Assurer l\'approvisionnement, la stabilité des prix et la décarbonation du mix énergétique européen dans un contexte de tension géopolitique accrue.',
      stat: '55%',
      statLabel: 'de dépendance aux imports gaziers en 2021',
      worksUrl: '#',
    },
    {
      id: 's-nucleaire',
      label: 'Nucléaire',
      type: 'subtheme',
      parentId: 'p-energie',
      depth: 2,
      title: 'Renaissance nucléaire',
      body: 'La France mise sur le prolongement du parc existant et les SMR. Douze pays UE forment une "Alliance nucléaire" pour peser dans la taxonomie verte.',
      stat: '56',
      statLabel: 'réacteurs en France, 1er parc européen',
    },
    {
      id: 's-renouvelables',
      label: 'Renouvelables',
      type: 'subtheme',
      parentId: 'p-energie',
      depth: 2,
      title: 'Transition renouvelable',
      body: 'L\'objectif 45% d\'ENR en 2030 exige une accélération sans précédent. Le Net-Zero Industry Act entend sécuriser la production de panneaux et éoliennes en Europe.',
      stat: '45%',
      statLabel: 'cible ENR dans le mix UE d\'ici 2030',
    },
    {
      id: 's-stockage',
      label: 'Stockage & réseau',
      type: 'subtheme',
      parentId: 'p-energie',
      depth: 2,
      title: 'Infrastructure de stockage',
      body: 'L\'intermittence des ENR rend critique le stockage et l\'interconnexion. Le projet IPCEI Hydrogène et les batteries européennes sont stratégiques.',
      stat: '€24Mds',
      statLabel: 'investissements batterie UE annoncés',
    },

    // Pillar 4 — Technologique (135°)
    {
      id: 'p-tech',
      label: 'Technologique',
      type: 'pillar',
      depth: 1,
      title: 'Souveraineté Technologique',
      body: 'Maîtriser les technologies de rupture — IA, semi-conducteurs, cloud, quantique — pour ne pas dépendre de plateformes étrangères dans les décisions critiques.',
      stat: '2%',
      statLabel: 'de la production mondiale de puces en UE',
      worksUrl: '#',
    },
    {
      id: 's-semis',
      label: 'Semi-conducteurs',
      type: 'subtheme',
      parentId: 'p-tech',
      depth: 2,
      title: 'Chips Act européen',
      body: 'L\'European Chips Act vise 20% de la production mondiale de semi-conducteurs d\'ici 2030. Intel à Magdebourg et TSMC à Dresde sont les premiers jalons.',
      stat: '20%',
      statLabel: 'part de marché mondial visée en 2030',
    },
    {
      id: 's-ia',
      label: 'Intelligence artificielle',
      type: 'subtheme',
      parentId: 'p-tech',
      depth: 2,
      title: 'IA souveraine',
      body: 'L\'IA Act pose un cadre réglementaire mais l\'Europe manque encore de champions d\'infrastructure. Mistral, Aleph Alpha et les supercalculateurs EuroHPC sont des signaux.',
      stat: '€20Mds',
      statLabel: 'investissements publics IA annoncés par la France',
    },
    {
      id: 's-cloud',
      label: 'Cloud & données',
      type: 'subtheme',
      parentId: 'p-tech',
      depth: 2,
      title: 'Souveraineté des données',
      body: 'GAIA-X et les labels SecNumCloud tentent de créer un écosystème cloud européen. Le défi : convaincre les entreprises de migrer depuis AWS et Azure.',
      stat: '72%',
      statLabel: 'du cloud UE capté par 3 acteurs US',
    },

    // Independent themes
    {
      id: 'indie-geopolitique',
      label: 'Géopolitique',
      type: 'indie',
      depth: 1,
      title: 'Environnement géopolitique',
      body: 'La guerre en Ukraine, les tensions en mer de Chine et la compétition sino-américaine redessinent les alliances et les chaînes d\'approvisionnement mondiales.',
      stat: '2022',
      statLabel: 'rupture stratégique en Europe',
    },
    {
      id: 'indie-finance',
      label: 'Finance & dette',
      type: 'indie',
      depth: 1,
      title: 'Autonomie financière',
      body: 'L\'euro numérique, l\'union des marchés de capitaux et le financement des transitions conditionnent la capacité d\'investissement européen à long terme.',
      stat: '€750Mds',
      statLabel: 'plan NextGenerationEU',
    },
  ],

  edges: [
    {
      id: 'e1',
      sourceId: 'p-indus',
      targetId: 'p-tech',
      label: 's\'appuie sur',
    },
    {
      id: 'e2',
      sourceId: 'p-energie',
      targetId: 'p-indus',
      label: 'alimente',
    },
    {
      id: 'e3',
      sourceId: 'p-tech',
      targetId: 'p-energie',
      label: 'optimise',
    },
    {
      id: 'e4',
      sourceId: 'p-alim',
      targetId: 'p-energie',
      label: 'consomme',
    },
    {
      id: 'e5',
      sourceId: 'p-indus',
      targetId: 'p-alim',
      label: 'mécanise',
    },
    {
      id: 'e6',
      sourceId: 'p-tech',
      targetId: 'p-alim',
      label: 'pilotée par',
    },
    {
      id: 'e7',
      sourceId: 'p-energie',
      targetId: 'p-tech',
      label: 'contraint',
    },
    {
      id: 'e8',
      sourceId: 's-semis',
      targetId: 's-defense',
      label: 'équipe',
    },
    {
      id: 'e9',
      sourceId: 's-renouvelables',
      targetId: 's-semis',
      label: 'dépend de',
    },
    {
      id: 'e10',
      sourceId: 'indie-geopolitique',
      targetId: 'p-indus',
      label: 'remodèle',
    },
  ],
};
