import type { ConstellationData } from './types';

export const DEFAULT_DATA: ConstellationData = {
  nodes: [
    // Hub
    {
      id: 'hub',
      label: 'LPE',
      type: 'hub',
      depth: 0,
      title: 'Laboratoire de la Puissance Européenne',
      body: 'Creuset d\'analyses stratégiques sur les souverainetés française et européenne. Nous cartographions les interdépendances qui structurent la puissance.',
      stat: '4',
      statLabel: 'piliers de souveraineté',
    },

    // Pillar 1 — Industrielle (225°)
    {
      id: 'p-indus',
      label: 'Industrielle',
      type: 'pillar',
      depth: 1,
      title: 'Souveraineté Industrielle',
      body: 'Capacité à concevoir, produire et maintenir sur le territoire européen les biens stratégiques : défense, mobilité, pharmacie, matériaux critiques.',
      stat: '38%',
      statLabel: 'de la valeur ajoutée UE perdue depuis 2000',
      worksUrl: '#',
    },
    {
      id: 's-defense',
      label: 'Défense & armement',
      type: 'subtheme',
      parentId: 'p-indus',
      depth: 2,
      title: 'Base industrielle de défense',
      body: 'L\'EDIP et le fonds européen de défense cherchent à consolider une BITD commune. Enjeu : interopérabilité et commandes mutualisées.',
      stat: '€100Mds',
      statLabel: 'investissements défense UE d\'ici 2030',
    },
    {
      id: 's-pharma',
      label: 'Pharma & santé',
      type: 'subtheme',
      parentId: 'p-indus',
      depth: 2,
      title: 'Réindustrialisation pharmaceutique',
      body: 'La dépendance asiatique pour les principes actifs a révélé la fragilité de la chaîne du médicament. Le projet IPCEI Santé entend corriger cela.',
      stat: '80%',
      statLabel: 'des APIs fabriqués hors Europe',
    },
    {
      id: 's-aerospace',
      label: 'Aéronautique & espace',
      type: 'subtheme',
      parentId: 'p-indus',
      depth: 2,
      title: 'Leadership aérospatial',
      body: 'Airbus, Ariane, MBDA : l\'Europe détient des pôles d\'excellence mais leur financement public reste insuffisant face à la concurrence américano-chinoise.',
      stat: '1er',
      statLabel: 'exportateur mondial d\'avions civils',
    },

    // Pillar 2 — Alimentaire (45°)
    {
      id: 'p-alim',
      label: 'Alimentaire',
      type: 'pillar',
      depth: 1,
      title: 'Souveraineté Alimentaire',
      body: 'Capacité à nourrir la population européenne avec une production locale résiliente, face au dérèglement climatique et aux chocs d\'approvisionnement.',
      stat: '27%',
      statLabel: 'des terres agricoles UE sous tension hydrique',
      worksUrl: '#',
    },
    {
      id: 's-pac',
      label: 'PAC & agriculture',
      type: 'subtheme',
      parentId: 'p-alim',
      depth: 2,
      title: 'Politique agricole commune',
      body: 'La PAC représente 31% du budget UE mais doit concilier compétitivité, transition verte et résilience. Sa réforme 2023 a arbitré en faveur de la production.',
      stat: '€387Mds',
      statLabel: 'budget PAC 2023–2027',
    },
    {
      id: 's-semences',
      label: 'Semences & biodiversité',
      type: 'subtheme',
      parentId: 'p-alim',
      depth: 2,
      title: 'Contrôle des semences',
      body: 'Quatre groupes contrôlent 60% du marché mondial des semences. La dépendance aux variétés hybrides brevetées fragilise l\'autonomie des agriculteurs.',
      stat: '4',
      statLabel: 'multinationales contrôlent 60% des semences',
    },
    {
      id: 's-eau',
      label: 'Eau & irrigation',
      type: 'subtheme',
      parentId: 'p-alim',
      depth: 2,
      title: 'Gestion de l\'eau agricole',
      body: 'L\'agriculture consomme 70% des prélèvements d\'eau douce en Europe. La compétition avec les usages urbains et industriels s\'intensifie.',
      stat: '70%',
      statLabel: 'de l\'eau douce dédiée à l\'agriculture',
    },

    // Pillar 3 — Énergétique (315°)
    {
      id: 'p-energie',
      label: 'Énergétique',
      type: 'pillar',
      depth: 1,
      title: 'Souveraineté Énergétique',
      body: 'Assurer l\'approvisionnement, la stabilité des prix et la décarbonation du mix énergétique européen dans un contexte de tension géopolitique accrue.',
      stat: '55%',
      statLabel: 'de dépendance aux imports gaziers en 2021',
      worksUrl: '#',
    },
    {
      id: 's-nucleaire',
      label: 'Nucléaire',
      type: 'subtheme',
      parentId: 'p-energie',
      depth: 2,
      title: 'Renaissance nucléaire',
      body: 'La France mise sur le prolongement du parc existant et les SMR. Douze pays UE forment une "Alliance nucléaire" pour peser dans la taxonomie verte.',
      stat: '56',
      statLabel: 'réacteurs en France, 1er parc européen',
    },
    {
      id: 's-renouvelables',
      label: 'Renouvelables',
      type: 'subtheme',
      parentId: 'p-energie',
      depth: 2,
      title: 'Transition renouvelable',
      body: 'L\'objectif 45% d\'ENR en 2030 exige une accélération sans précédent. Le Net-Zero Industry Act entend sécuriser la production de panneaux et éoliennes en Europe.',
      stat: '45%',
      statLabel: 'cible ENR dans le mix UE d\'ici 2030',
    },
    {
      id: 's-stockage',
      label: 'Stockage & réseau',
      type: 'subtheme',
      parentId: 'p-energie',
      depth: 2,
      title: 'Infrastructure de stockage',
      body: 'L\'intermittence des ENR rend critique le stockage et l\'interconnexion. Le projet IPCEI Hydrogène et les batteries européennes sont stratégiques.',
      stat: '€24Mds',
      statLabel: 'investissements batterie UE annoncés',
    },

    // Pillar 4 — Technologique (135°)
    {
      id: 'p-tech',
      label: 'Technologique',
      type: 'pillar',
      depth: 1,
      title: 'Souveraineté Technologique',
      body: 'Maîtriser les technologies de rupture — IA, semi-conducteurs, cloud, quantique — pour ne pas dépendre de plateformes étrangères dans les décisions critiques.',
      stat: '2%',
      statLabel: 'de la production mondiale de puces en UE',
      worksUrl: '#',
    },
    {
      id: 's-semis',
      label: 'Semi-conducteurs',
      type: 'subtheme',
      parentId: 'p-tech',
      depth: 2,
      title: 'Chips Act européen',
      body: 'L\'European Chips Act vise 20% de la production mondiale de semi-conducteurs d\'ici 2030. Intel à Magdebourg et TSMC à Dresde sont les premiers jalons.',
      stat: '20%',
      statLabel: 'part de marché mondial visée en 2030',
    },
    {
      id: 's-ia',
      label: 'Intelligence artificielle',
      type: 'subtheme',
      parentId: 'p-tech',
      depth: 2,
      title: 'IA souveraine',
      body: 'L\'IA Act pose un cadre réglementaire mais l\'Europe manque encore de champions d\'infrastructure. Mistral, Aleph Alpha et les supercalculateurs EuroHPC sont des signaux.',
      stat: '€20Mds',
      statLabel: 'investissements publics IA annoncés par la France',
    },
    {
      id: 's-cloud',
      label: 'Cloud & données',
      type: 'subtheme',
      parentId: 'p-tech',
      depth: 2,
      title: 'Souveraineté des données',
      body: 'GAIA-X et les labels SecNumCloud tentent de créer un écosystème cloud européen. Le défi : convaincre les entreprises de migrer depuis AWS et Azure.',
      stat: '72%',
      statLabel: 'du cloud UE capté par 3 acteurs US',
    },

    // ── COMPANIES ──────────────────────────────────────────────────────

    // Pharma → Sanofi
    {
      id: 'c-sanofi',
      label: 'Sanofi',
      type: 'company',
      parentId: 's-pharma',
      depth: 3,
      title: 'Sanofi',
      body: 'Premier groupe pharmaceutique français, Sanofi opère dans les vaccins, l\'immunologie et les maladies rares. CA 2023 : €43Mds. Siège : Paris.',
      stat: '€43Mds',
      statLabel: 'chiffre d\'affaires 2023',
    },
    // Pharma → AstraZeneca France
    {
      id: 'c-astra',
      label: 'AstraZeneca',
      type: 'company',
      parentId: 's-pharma',
      depth: 3,
      title: 'AstraZeneca France',
      body: 'Filiale française du groupe anglo-suédois, positionnée sur l\'oncologie, les maladies cardiovasculaires et les vaccins. Présente en France depuis 1992.',
      stat: '6 000',
      statLabel: 'collaborateurs en France',
    },

    // Semi-conducteurs → STMicroelectronics
    {
      id: 'c-st',
      label: 'STMicro',
      type: 'company',
      parentId: 's-semis',
      depth: 3,
      title: 'STMicroelectronics',
      body: 'Champion franco-italien des semi-conducteurs, présent dans l\'automobile, l\'IoT et l\'industrie. Fab à Crolles (France) et Catane (Italie).',
      stat: '€17Mds',
      statLabel: 'revenus 2023',
    },
    // Semi-conducteurs → ASML
    {
      id: 'c-asml',
      label: 'ASML',
      type: 'company',
      parentId: 's-semis',
      depth: 3,
      title: 'ASML',
      body: 'Monopole mondial des machines EUV (lithographie extrême UV). Sans ASML, aucune puce de moins de 7nm ne peut être fabriquée dans le monde.',
      stat: '100%',
      statLabel: 'des puces avancées mondiales dépendent d\'ASML',
    },

    // Renouvelables → TotalEnergies
    {
      id: 'c-total',
      label: 'TotalEnergies',
      type: 'company',
      parentId: 's-renouvelables',
      depth: 3,
      title: 'TotalEnergies',
      body: 'Major pétro-gazière en transition vers les ENR : éolien offshore, solaire, hydrogène. Ambition 100 GW de capacités renouvelables d\'ici 2030.',
      stat: '100 GW',
      statLabel: 'objectif ENR 2030',
    },

    // Aéronautique → Airbus
    {
      id: 'c-airbus',
      label: 'Airbus',
      type: 'company',
      parentId: 's-aerospace',
      depth: 3,
      title: 'Airbus',
      body: 'Champion européen de l\'aéronautique civile et de défense. Siège à Toulouse. Développe l\'avion à hydrogène ZEROe pour 2035.',
      stat: '780',
      statLabel: 'avions livrés en 2023',
    },

    // ── PEOPLE ──────────────────────────────────────────────────────────

    // Sanofi people
    {
      id: 'p-marchetti',
      label: 'P. Marchetti',
      type: 'person',
      parentId: 'c-sanofi',
      depth: 4,
      title: 'Paul Marchetti',
      body: 'Dirige la R&D vaccins en Europe. Coordonne les programmes mRNA post-Covid et les essais cliniques phase III.',
      personPosition: 'Directeur R&D Vaccins',
      personEmail: 'p.marchetti@sanofi.com',
      personPhone: '+33 1 53 77 41 01',
      personCompany: 'Sanofi',
      stat: '18 ans',
      statLabel: 'chez Sanofi',
    },
    {
      id: 'p-fontaine',
      label: 'I. Fontaine',
      type: 'person',
      parentId: 'c-sanofi',
      depth: 4,
      title: 'Isabelle Fontaine',
      body: 'Supervise les dossiers d\'AMM en Europe et les négociations avec l\'EMA. Ancienne inspectrice ANSM.',
      personPosition: 'VP Affaires Réglementaires',
      personEmail: 'i.fontaine@sanofi.com',
      personPhone: '+33 1 53 77 42 88',
      personCompany: 'Sanofi',
      stat: 'EMA',
      statLabel: 'membre du comité consultatif',
    },
    {
      id: 'p-lebrun',
      label: 'T. Lebrun',
      type: 'person',
      parentId: 'c-sanofi',
      depth: 4,
      title: 'Thomas Lebrun',
      body: 'Pilote les alliances industrielles de Sanofi avec d\'autres groupes pharmaceutiques et biotechs européennes.',
      personPosition: 'Dir. Partenariats Stratégiques',
      personEmail: 't.lebrun@sanofi.com',
      personPhone: '+33 1 53 77 43 12',
      personCompany: 'Sanofi',
      stat: '12',
      statLabel: 'partenariats actifs en Europe',
    },

    // AstraZeneca people
    {
      id: 'p-delacroix',
      label: 'S. Delacroix',
      type: 'person',
      parentId: 'c-astra',
      depth: 4,
      title: 'Sophie Delacroix',
      body: 'Responsable de la stratégie médicale d\'AZ en France. Coordonne les études de vie réelle et les relations avec les KOLs.',
      personPosition: 'Directrice Médicale France',
      personEmail: 's.delacroix@astrazeneca.com',
      personPhone: '+33 1 41 29 40 00',
      personCompany: 'AstraZeneca France',
      stat: 'Oncologie',
      statLabel: 'domaine thérapeutique principal',
    },
    {
      id: 'p-nguyen',
      label: 'M. Nguyen',
      type: 'person',
      parentId: 'c-astra',
      depth: 4,
      title: 'Marc Nguyen',
      body: 'Négocie les accords de remboursement avec la HAS et le CEPS. Spécialiste des modèles d\'accès précoce.',
      personPosition: 'Responsable Market Access',
      personEmail: 'm.nguyen@astrazeneca.com',
      personPhone: '+33 1 41 29 40 15',
      personCompany: 'AstraZeneca France',
      stat: 'HAS',
      statLabel: 'interlocuteur principal',
    },

    // STMicroelectronics people
    {
      id: 'p-russo',
      label: 'A. Russo',
      type: 'person',
      parentId: 'c-st',
      depth: 4,
      title: 'Antoine Russo',
      body: 'Dirige les équipes d\'ingénierie produit pour les marchés automobiles et industriels en Europe. Basé à Crolles.',
      personPosition: 'VP Engineering Europe',
      personEmail: 'a.russo@st.com',
      personPhone: '+33 4 76 58 30 00',
      personCompany: 'STMicroelectronics',
      stat: '1 200',
      statLabel: 'ingénieurs sous sa direction',
    },
    {
      id: 'p-petit',
      label: 'C. Petit',
      type: 'person',
      parentId: 'c-st',
      depth: 4,
      title: 'Clara Petit',
      body: 'Pilote les programmes d\'open innovation et les partenariats avec les labos CEA-Leti et IMEC pour les nœuds sub-7nm.',
      personPosition: 'Directrice Innovation',
      personEmail: 'c.petit@st.com',
      personPhone: '+33 4 76 58 31 44',
      personCompany: 'STMicroelectronics',
      stat: 'CEA-Leti',
      statLabel: 'partenaire R&D clé',
    },
    {
      id: 'p-amrani',
      label: 'K. Amrani',
      type: 'person',
      parentId: 'c-st',
      depth: 4,
      title: 'Karim Amrani',
      body: 'Coordonne les programmes de thèse CIFRE et les chaires avec Polytechnique, CentraleSupélec et l\'EPFL.',
      personPosition: 'Resp. Partenariats Académiques',
      personEmail: 'k.amrani@st.com',
      personPhone: '+33 4 76 58 32 07',
      personCompany: 'STMicroelectronics',
      stat: '23',
      statLabel: 'thèses CIFRE en cours',
    },

    // TotalEnergies people
    {
      id: 'p-moreau',
      label: 'J.-B. Moreau',
      type: 'person',
      parentId: 'c-total',
      depth: 4,
      title: 'Jean-Baptiste Moreau',
      body: 'Architecte de la feuille de route Net Zéro de TotalEnergies. Ancien conseiller énergie à l\'Élysée (2018–2021).',
      personPosition: 'Dir. Transition Énergétique',
      personEmail: 'jb.moreau@totalenergies.com',
      personPhone: '+33 1 47 44 45 46',
      personCompany: 'TotalEnergies',
      stat: 'Net Zéro',
      statLabel: 'horizon 2050',
    },
    {
      id: 'p-voss',
      label: 'H. Voss',
      type: 'person',
      parentId: 'c-total',
      depth: 4,
      title: 'Hélène Voss',
      body: 'Supervise les projets éolien offshore en mer du Nord et en Méditerranée. Responsable des JV avec Ørsted et Iberdrola.',
      personPosition: 'VP Renouvelables Europe',
      personEmail: 'h.voss@totalenergies.com',
      personPhone: '+33 1 47 44 46 12',
      personCompany: 'TotalEnergies',
      stat: '8 GW',
      statLabel: 'portefeuille éolien offshore géré',
    },

    // Airbus people
    {
      id: 'p-dufour',
      label: 'P. Dufour',
      type: 'person',
      parentId: 'c-airbus',
      depth: 4,
      title: 'Pierre Dufour',
      body: 'Pilote les programmes A400M, Eurofighter et les démonstrateurs de défense FCAS. Interface principale avec la DGA et les ministères.',
      personPosition: 'VP Programmes Défense',
      personEmail: 'p.dufour@airbus.com',
      personPhone: '+33 5 61 93 33 33',
      personCompany: 'Airbus',
      stat: 'FCAS',
      statLabel: 'programme de référence',
    },
    {
      id: 'p-schmidt',
      label: 'L. Schmidt',
      type: 'person',
      parentId: 'c-airbus',
      depth: 4,
      title: 'Laura Schmidt',
      body: 'Gère les relations avec la Commission européenne, le Parlement et les ministères nationaux. Coordonne les positions Airbus sur les réglementations aviation.',
      personPosition: 'Dir. Relations Institutionnelles',
      personEmail: 'l.schmidt@airbus.com',
      personPhone: '+33 5 61 93 34 56',
      personCompany: 'Airbus',
      stat: 'Bruxelles',
      statLabel: 'bureau principal de lobbying',
    },

    // Independent themes
    {
      id: 'indie-geopolitique',
      label: 'Géopolitique',
      type: 'indie',
      depth: 1,
      title: 'Environnement géopolitique',
      body: 'La guerre en Ukraine, les tensions en mer de Chine et la compétition sino-américaine redessinent les alliances et les chaînes d\'approvisionnement mondiales.',
      stat: '2022',
      statLabel: 'rupture stratégique en Europe',
    },
    {
      id: 'indie-finance',
      label: 'Finance & dette',
      type: 'indie',
      depth: 1,
      title: 'Autonomie financière',
      body: 'L\'euro numérique, l\'union des marchés de capitaux et le financement des transitions conditionnent la capacité d\'investissement européen à long terme.',
      stat: '€750Mds',
      statLabel: 'plan NextGenerationEU',
    },
  ],

  edges: [
    {
      id: 'e1',
      sourceId: 'p-indus',
      targetId: 'p-tech',
      label: 's\'appuie sur',
    },
    {
      id: 'e2',
      sourceId: 'p-energie',
      targetId: 'p-indus',
      label: 'alimente',
    },
    {
      id: 'e3',
      sourceId: 'p-tech',
      targetId: 'p-energie',
      label: 'optimise',
    },
    {
      id: 'e4',
      sourceId: 'p-alim',
      targetId: 'p-energie',
      label: 'consomme',
    },
    {
      id: 'e5',
      sourceId: 'p-indus',
      targetId: 'p-alim',
      label: 'mécanise',
    },
    {
      id: 'e6',
      sourceId: 'p-tech',
      targetId: 'p-alim',
      label: 'pilotée par',
    },
    {
      id: 'e7',
      sourceId: 'p-energie',
      targetId: 'p-tech',
      label: 'contraint',
    },
    {
      id: 'e8',
      sourceId: 's-semis',
      targetId: 's-defense',
      label: 'équipe',
    },
    {
      id: 'e9',
      sourceId: 's-renouvelables',
      targetId: 's-semis',
      label: 'dépend de',
    },
    {
      id: 'e10',
      sourceId: 'indie-geopolitique',
      targetId: 'p-indus',
      label: 'remodèle',
    },

    // ── Liens inter-personnes ──────────────────────────────────────────
    {
      id: 'ep1',
      sourceId: 'p-lebrun',
      targetId: 'p-nguyen',
      label: 'partenariat API',
    },
    {
      id: 'ep2',
      sourceId: 'p-marchetti',
      targetId: 'p-delacroix',
      label: 'groupe de travail',
    },
    {
      id: 'ep3',
      sourceId: 'p-fontaine',
      targetId: 'p-delacroix',
      label: 'comité EMA commun',
    },
    {
      id: 'ep4',
      sourceId: 'p-russo',
      targetId: 'p-petit',
      label: 'co-dirige',
    },
    {
      id: 'ep5',
      sourceId: 'p-amrani',
      targetId: 'p-russo',
      label: 'rapporte à',
    },
    {
      id: 'ep6',
      sourceId: 'p-moreau',
      targetId: 'p-voss',
      label: 'dirige',
    },
    {
      id: 'ep7',
      sourceId: 'p-voss',
      targetId: 'p-dufour',
      label: 'hydrogène aviation',
    },
    {
      id: 'ep8',
      sourceId: 'p-schmidt',
      targetId: 'p-lebrun',
      label: 'lobbying commun',
    },
    {
      id: 'ep9',
      sourceId: 'p-petit',
      targetId: 'p-amrani',
      label: 'programme CIFRE',
    },
    {
      id: 'ep10',
      sourceId: 'p-dufour',
      targetId: 'p-russo',
      label: 'semi-conducteurs défense',
    },
    {
      id: 'ep11',
      sourceId: 'p-moreau',
      targetId: 'p-schmidt',
      label: 'task force H2',
    },
  ],
};
